install.packages("igraph", repos = "http://cran.cnr.berkeley.edu/", dependencies = TRUE)
install.packages("sna", repos = "http://cran.cnr.berkeley.edu/", dependencies = TRUE)
install.packages("tm", repos = "http://cran.cnr.berkeley.edu/", dependencies = TRUE)
install.packages("stringi", repos = "http://cran.cnr.berkeley.edu/", dependencies = TRUE)
install.packages("proxy", repos = "http://cran.cnr.berkeley.edu/", dependencies = TRUE)
install.packages("rgl", repos = "http://cran.cnr.berkeley.edu/", dependencies = TRUE)
install.packages("NetData", repos = "http://cran.cnr.berkeley.edu/", dependencies = TRUE)
install.packages("devtools", repos = "http://cran.cnr.berkeley.edu/", dependencies = TRUE)
install.packages("RCurl", repos = "http://cran.cnr.berkeley.edu/", dependencies = TRUE)
install.packages("sqldf", repos = "http://cran.cnr.berkeley.edu/", dependencies = TRUE)
install.packages("wordcloud", repos = "http://cran.cnr.berkeley.edu/", dependencies = TRUE)
library("devtools")
install_github("pablobarbera/Rfacebook", subdir="Rfacebook")
install_github("geoffjentry/twitteR")
install_github("mpiccirilli/Rlinkedin")
install.packages("xml2", repos = "http://cran.cnr.berkeley.edu/", dependencies = TRUE)
